theme: jekyll-theme-minimal
title: DuckDuck(UK) Open Resource Library
description: Although free, the items found on this resource collection may still adhere to opensource licensing rules. Please be sure that you understand these licenses before using or distributing items found on this platform.
